Resources:
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: storage-bucket-${self:custom.identifier}

Outputs:
  StorageBucketName:
    Value: !Ref StorageBucket
    Export:
      Name: StorageBucket-${self:custom.identifier}-BucketName
  StorageBucketArn:
    Value: !GetAtt
      - StorageBucket
      - Arn
    Export:
      Name: StorageBucket-${self:custom.identifier}-BucketArn
